<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
require_once __DIR__ . '/Base/MixpanelBase.php';
require_once __DIR__ . '/ConsumerStrategies/AbstractConsumer.php';
require_once __DIR__ . '/ConsumerStrategies/CurlConsumer.php';
require_once __DIR__ . '/ConsumerStrategies/FileConsumer.php';
require_once __DIR__ . '/ConsumerStrategies/SocketConsumer.php';
require_once __DIR__ . '/Exception.php';
require_once __DIR__ . '/Mixpanel.php';
require_once __DIR__ . '/Producers/MixpanelBaseProducer.php';
require_once __DIR__ . '/Producers/MixpanelEvents.php';
require_once __DIR__ . '/Producers/MixpanelPeople.php';
// @codeCoverageIgnoreEnd
require_once __DIR__ . "/compat.php";
